language: python
env:
    - PYTHON=2.7
    - PYTHON=3.5
    - PYTHON=3.6
    - PYTHON=3.7
before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
    - conda create -n testenv --yes pip python=$PYTHON
    - source activate testenv
    - conda install --yes --file requirements.txt
    - pip install black
    - python setup.py develop
script:
    - py.test --cov=pyglmnet tests/
    - flake8 --count pyglmnet
    # Run the black code formatter to check if code adheres
    - black tests pyglmnet --check --line-length 79
after_success:
    - bash <(curl -s https://codecov.io/bash)
